# Generated by Django 4.1.7 on 2023-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplan',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipeplan',
            name='recipes',
            field=models.ManyToManyField(related_name='plans', to='recipes.recipes'),
        ),
    ]
