# Generated by Django 4.1.7 on 2023-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipeplan_recipes_recipeplan_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=models.ImageField(blank=True, default='recipes/placeholder.png', null=True, upload_to='recipes/'),
        ),
    ]
