# Generated by Django 4.1.7 on 2023-03-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipes_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ('ingredient_id',)},
        ),
    ]
