# Generated by Django 4.1.7 on 2023-03-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ('ingredient',)},
        ),
    ]
