# Generated by Django 4.1.7 on 2023-03-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',)},
        ),
    ]
